name: task_pro
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+15

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  device_preview: ^1.1.0
  flutter_plugin_android_lifecycle: ^2.0.5
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.11
  connectivity: ^3.0.6
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_core_platform_interface: 4.5.2
  firebase_messaging: ^14.2.1
  flutter_svg:
  cached_network_image: ^3.2.1
  url_launcher: ^6.1.2
  shimmer_animation: ^2.1.0+1
  flutter_html: 3.0.0-alpha.6
  flutter_local_notifications: ^9.5.3+1
  google_fonts:
  pinput: ^3.0.1
  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.3
  webview_flutter: ^4.4.2
  font_awesome_flutter:
  image_picker:
  image_compression_flutter: ^1.0.2
  device_info_plus: ^9.0.2
  sms_autofill: ^2.3.0
  screenshot: 1.3.0
  image_gallery_saver: '^2.0.3'
  permission_handler: ^10.4.3
  path_provider: ^2.0.15
  flutter_inappwebview: ^5.8.0
  in_app_update: ^4.1.4
  youtube_player_flutter: ^8.1.2
  timer_count_down: ^2.2.2
  video_player: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/video/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
