class Autogenerated {
  bool? success;
  List<AllTaskModel>? data;
  String? message;

  Autogenerated({this.success, this.data, this.message});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      data = <AllTaskModel>[];
      json['data'].forEach((v) {
        data!.add(new AllTaskModel.fromJson(v));
      });
    }
    message = json['message'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['message'] = this.message;
    return data;
  }
}

class AllTaskModel {
  String? assignedAt;
  List<TaskList>? taskList;
  int? completedTask;
  int? inCompletedTask;
  String? taskProgress;

  AllTaskModel({
    this.assignedAt,
    this.taskList,
    this.completedTask,
    this.inCompletedTask,
    this.taskProgress,
  });

  AllTaskModel.fromJson(Map<String, dynamic> json) {
    assignedAt = json['assigned_at'];
    completedTask = json['completed'];
    inCompletedTask = json['incomplete'];
    taskProgress = json['task_progess'];
    if (json['task_list'] != null) {
      taskList = <TaskList>[];
      json['task_list'].forEach((v) {
        taskList!.add(new TaskList.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['assigned_at'] = this.assignedAt;
    data['completed'] = this.completedTask;
    data['incomplete'] = this.inCompletedTask;
    data['task_progess'] = this.taskProgress;
    if (this.taskList != null) {
      data['task_list'] = this.taskList!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class TaskList {
  int? id;
  int? userId;
  int? taskId;
  String? description;
  String? assignedAt;
  String? status;
  Null? deletedAt;
  String? createdAt;
  String? updatedAt;
  Task? task;

  TaskList(
      {this.id,
        this.userId,
        this.taskId,
        this.description,
        this.assignedAt,
        this.status,
        this.deletedAt,
        this.createdAt,
        this.updatedAt,
        this.task});

  TaskList.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userId = json['user_id'];
    taskId = json['task_id'];
    description = json['description'];
    assignedAt = json['assigned_at'];
    status = json['status'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    task = json['task'] != null ? new Task.fromJson(json['task']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['user_id'] = this.userId;
    data['task_id'] = this.taskId;
    data['description'] = this.description;
    data['assigned_at'] = this.assignedAt;
    data['status'] = this.status;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.task != null) {
      data['task'] = this.task!.toJson();
    }
    return data;
  }
}

class Task {
  int? id;
  String? title;
  String? description;
  String? taskValidity;
  String? taskType;
  String? url;
  String? instruction;
  Null? deletedAt;
  String? createdAt;
  String? updatedAt;

  Task(
      {this.id,
        this.title,
        this.description,
        this.taskValidity,
        this.taskType,
        this.url,
        this.instruction,
        this.deletedAt,
        this.createdAt,
        this.updatedAt});

  Task.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    description = json['description'];
    taskValidity = json['task_validity'];
    taskType = json['task_type'];
    url = json['url'];
    instruction = json['instruction'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['description'] = this.description;
    data['task_validity'] = this.taskValidity;
    data['task_type'] = this.taskType;
    data['url'] = this.url;
    data['instruction'] = this.instruction;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}
