class Autogenerated {
  bool? success;
  TaskModel? data;
  String? message;

  Autogenerated({this.success, this.data, this.message});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = json['data'] != null ? new TaskModel.fromJson(json['data']) : null;
    message = json['message'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = this.message;
    return data;
  }
}

class TaskModel {
  int? completed;
  int? incomplete;
  String? taskProgess;
  List<TaskListModel>? taskList;

  TaskModel({this.completed, this.incomplete, this.taskProgess, this.taskList});

  TaskModel.fromJson(Map<String, dynamic> json) {
    completed = json['completed'];
    incomplete = json['incomplete'];
    taskProgess = json['task_progess'];
    if (json['task_list'] != null) {
      taskList = <TaskListModel>[];
      json['task_list'].forEach((v) {
        taskList!.add(new TaskListModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['completed'] = this.completed;
    data['incomplete'] = this.incomplete;
    data['task_progess'] = this.taskProgess;
    if (this.taskList != null) {
      data['task_list'] = this.taskList!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class TaskListModel {
  int? id;
  int? userId;
  int? taskId;
  String? description;
  String? assignedAt;
  String? verifiedAt;
  String? completedAt;
  String? status;
  String? screenShotRejectDes;
  Null? deletedAt;
  String? createdAt;
  String? updatedAt;
  String? verifyImageUrl;
  Task? task;
  User? user;
  HowToVideo? howToVideo;

  TaskListModel(
      {this.id,
        this.userId,
        this.taskId,
        this.description,
        this.assignedAt,
        this.verifiedAt,
        this.completedAt,
        this.status,
        this.screenShotRejectDes,
        this.deletedAt,
        this.createdAt,
        this.updatedAt,
        this.task,
        this.verifyImageUrl,
        this.user,
        this.howToVideo,
      });

  TaskListModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userId = json['user_id'];
    taskId = json['task_id'];
    description = json['description'];
    assignedAt = json['assigned_at'];
    verifiedAt = json['verified_at'];
    completedAt = json['completed_at'];
    status = json['status'];
    screenShotRejectDes = json['screenshot_reject_note'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    verifyImageUrl = json['verify_image_url'];
    howToVideo = json['how_to_video'] != null
        ? new HowToVideo.fromJson(json['how_to_video'])
        : null;
    task = json['task'] != null ? new Task.fromJson(json['task']) : null;
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['user_id'] = this.userId;
    data['task_id'] = this.taskId;
    data['description'] = this.description;
    data['assigned_at'] = this.assignedAt;
    data['verified_at'] = this.verifiedAt;
    data['completed_at'] = this.completedAt;
    data['status'] = this.status;
    data['screenshot_reject_note'] = this.screenShotRejectDes;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['verify_image_url'] = this.verifyImageUrl;
    if (this.howToVideo != null) {
      data['how_to_video'] = this.howToVideo!.toJson();
    }
    if (this.task != null) {
      data['task'] = this.task!.toJson();
    }
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    return data;
  }
}

class HowToVideo {
  String? videoUrl;
  String? title;
  String? descirption;
  String? howToDo;

  HowToVideo({this.videoUrl, this.title, this.descirption, this.howToDo});

  HowToVideo.fromJson(Map<String, dynamic> json) {
    videoUrl = json['video_url'];
    title = json['title'];
    descirption = json['descirption'];
    howToDo = json['how_to_do'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['video_url'] = this.videoUrl;
    data['title'] = this.title;
    data['descirption'] = this.descirption;
    data['how_to_do'] = this.howToDo;
    return data;
  }
}

class Task {
  int? id;
  String? title;
  String? businessName;
  String? description;
  String? taskValidity;
  String? taskType;
  String? url;
  String? instruction;
  Null? deletedAt;
  String? createdAt;
  String? updatedAt;
  List<Comments>? comments;

  Task(
      {this.id,
        this.title,
        this.businessName,
        this.description,
        this.taskValidity,
        this.taskType,
        this.url,
        this.instruction,
        this.deletedAt,
        this.createdAt,
        this.updatedAt,
        this.comments});

  Task.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    businessName = json['business_name'];
    description = json['description'];
    taskValidity = json['task_validity'];
    taskType = json['task_type'];
    url = json['url'];
    instruction = json['instruction'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    if (json['comments'] != null) {
      comments = <Comments>[];
      json['comments'].forEach((v) {
        comments!.add(new Comments.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['business_name'] = this.businessName;
    data['description'] = this.description;
    data['task_validity'] = this.taskValidity;
    data['task_type'] = this.taskType;
    data['url'] = this.url;
    data['instruction'] = this.instruction;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.comments != null) {
      data['comments'] = this.comments!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Comments {
  int? id;
  int? taskId;
  String? comment;
  String? isUsed;
  Null? deletedAt;
  String? createdAt;
  String? updatedAt;

  Comments(
      {this.id,
        this.taskId,
        this.comment,
        this.isUsed,
        this.deletedAt,
        this.createdAt,
        this.updatedAt});

  Comments.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    taskId = json['task_id'];
    comment = json['comment'];
    isUsed = json['is_used'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['task_id'] = this.taskId;
    data['comment'] = this.comment;
    data['is_used'] = this.isUsed;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}

class User {
  int? id;
  String? name;
  String? mobileNo;
  String? email;
  Null? emailVerifiedAt;
  String? recordPath;
  String? role;
  String? date;
  String? referBy;
  String? referName;
  Null? deletedAt;
  String? createdAt;
  String? updatedAt;

  User(
      {this.id,
        this.name,
        this.mobileNo,
        this.email,
        this.emailVerifiedAt,
        this.recordPath,
        this.role,
        this.date,
        this.referBy,
        this.referName,
        this.deletedAt,
        this.createdAt,
        this.updatedAt});

  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    mobileNo = json['mobile_no'];
    email = json['email'];
    emailVerifiedAt = json['email_verified_at'];
    recordPath = json['record_path'];
    role = json['role'];
    date = json['date'];
    referBy = json['refer_by'];
    referName = json['refer_name'];
    deletedAt = json['deleted_at'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['mobile_no'] = this.mobileNo;
    data['email'] = this.email;
    data['email_verified_at'] = this.emailVerifiedAt;
    data['record_path'] = this.recordPath;
    data['role'] = this.role;
    data['date'] = this.date;
    data['refer_by'] = this.referBy;
    data['refer_name'] = this.referName;
    data['deleted_at'] = this.deletedAt;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}
